name: zelus_ui
description: Shared UI components and theme for Zelus apps
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  zelus_core:
    path: ../zelus_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

