name: zelus_api
description: Shared API client and data models for Zelus apps
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Networking
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Serialization
  freezed_annotation: ^2.4.1
  
  # Utils
  logger: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  freezed: ^2.4.5
  flutter_lints: ^3.0.1

